url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Folk Ridge" # the name of your site, e.g. ACME Corp.


exclude: ["source", "node_modules", "mix-manifest.json", "package-lock.json", "package.json", "webpack.mix.js", ".jekyll-cache"]

plugins:  
  - jekyll-feed
  - jekyll-strapi

strapi:  
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: https://strapi-folkridge.herokuapp.com
    collections:
        # Example for a "posts" collection
        posts:
            # Collection name (optional). Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
            type: posts
            # Permalink used to generate the output files (eg. /posts/:id).
            permalink: /posts/:slug/
        pages:
          type: pages

        bandmembers:
          type: bandmembers
        instruments:
          type: instruments
        packages:
          type: packages
        socials:
          type: socials
        contacts:
          type: contacts
        page-metas:
          type: page-metas
          

          